spring.application.name=realtime-notification
server.port=8081

## PostgreSQL Connection Settings (Aligned to your SCMS tables)
spring.datasource.url=jdbc:postgresql://localhost:5432/project
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

## Tells Hibernate where to scan for your tables
spring.datasource.hikari.connection-init-sql=SET search_path TO public,masters,config;

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true