package com.intern.notification.repository;

import com.intern.notification.model.Notification;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface NotificationRepository extends JpaRepository<Notification, Long>{
// Basic CRUD operations are instantly generated by JpaRepository
}
